# Generated by Django 4.2.7 on 2023-11-08 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255)),
                ('student_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('work_ethic', models.IntegerField(default=0)),
                ('timeliness', models.IntegerField(default=0)),
                ('leadership_skills', models.IntegerField(default=0)),
                ('charisma', models.IntegerField(default=0)),
                ('agreeable', models.IntegerField(default=0)),
                ('pragmatic', models.BooleanField(default=False)),
                ('reliability', models.IntegerField(default=0)),
                ('trustworthiness', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='reviewApp.student')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to='reviewApp.student')),
            ],
        ),
    ]
