# Generated by Django 4.2.7 on 2023-11-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0003_review_agreeable_review_charisma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='class_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
