# Generated by Django 4.2.7 on 2023-11-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0004_review_class_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='project_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
