# Generated by Django 4.2.7 on 2023-11-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0005_review_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='student_id',
            field=models.IntegerField(default=1),
        ),
    ]
