# Generated by Django 4.2.7 on 2023-11-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0010_alter_review_agreeable_alter_review_charisma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='instructor_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='instructor',
            name='university',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.CharField(default='', max_length=255),
        ),
    ]
