# Generated by Django 4.2.7 on 2023-11-13 14:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0013_remove_instructor_reviewer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='articulate',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='charisma',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='hard_grader',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='interesting',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='student_reviewer',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='teaching_ability',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='text',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='timeliness',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instructor_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='InstructorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=1000)),
                ('teaching_ability', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('hard_grader', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('articulate', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('charisma', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('interesting', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('timeliness', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='reviewApp.instructor')),
                ('student_reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_instructor_reviews', to='reviewApp.student')),
            ],
        ),
    ]
