# Generated by Django 4.2.7 on 2023-11-13 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0014_remove_instructor_articulate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorreview',
            name='student_reviewer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_instructor_reviews', to='reviewApp.student'),
        ),
    ]
