# Generated by Django 4.2.7 on 2023-11-13 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0017_alter_instructor_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='class_taught',
        ),
        migrations.AddField(
            model_name='instructorreview',
            name='class_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='instructorreview',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
